[build]
target = "riscv64imac-unknown-none-elf"

[target.riscv64imac-unknown-none-elf]
rustflags = [
    "-C", "link-arg=-Tsrc/linker.ld",
    # "-C", "link-arg=--relax",
    # "-C", "target-feature=+relax",
    # "-C", "force-frame-pointers=yes", # using s0 to save stack-frame
]

# [source.crates-io]
# replace-with = "vendored-sources"

# [source.vendored-sources]
# directory = "../dependencies/vendor"
