[package]
name = "ftl-util"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"

[features]
default = []
stack_trace = []
libc_output = [] # 这个feature可以在测试时用libc的putchar输出
